const FrameDefine = {
	APPEAR_FRAMES: [
		{ rockY: 17, state: 'stick' },
		{ rockY: 33, state: 'stick' },
		{ rockY: 49, state: 'stick' },
		{ rockY: 65, state: 'stick' },
		{ rockY: 81, state: 'stick' },
		{ rockY: 97, state: 'stick' },
		{ rockY: 113, state: 'stick' },
		{ rockY: 129, state: 'stick' },
		{ rockY: 129, state: 'stick' },
		{ rockY: 128, state: 'stick' },
		{ rockY: 127, state: 'divided' },
		{ rockY: 127, state: 'divided' },
		{ rockY: 127, state: 'divided' },
		{ rockY: 128, state: 'shrink' },
		{ rockY: 128, state: 'shrink' },
		{ rockY: 129, state: 'shrink' },
		{ rockY: 129, state: 'stick' },
		{ rockY: 129, state: 'stick' },
		{ rockY: 129, state: 'stick' },
		{ rockY: 129, state: 'normal' },
	],
	START_TO_RIGHT_FRAMES: [
		{ rockX: 13, direction: 'right', state: 'normal' },
		{ rockX: 13, direction: 'right', state: 'normal' },
		{ rockX: 13, direction: 'right', state: 'normal' },
		{ rockX: 13, direction: 'right', state: 'normal' },
		{ rockX: 13, direction: 'right', state: 'normal' },
		{ rockX: 13, direction: 'right', state: 'pull' },
		{ rockX: 13, direction: 'right', state: 'pull' },
		{ rockX: 13, direction: 'right', state: 'pull' },
		{ rockX: 13, direction: 'right', state: 'pull' },
		{ rockX: 13, direction: 'right', state: 'pull' },
		{ rockX: 14, direction: 'right', state: 'run0' },
		{ rockX: 16, direction: 'right', state: 'run0' },
		{ rockX: 17, direction: 'right', state: 'run0' },
		{ rockX: 19, direction: 'right', state: 'run0' },
		{ rockX: 20, direction: 'right', state: 'run0' },
		{ rockX: 22, direction: 'right', state: 'run0' },
		{ rockX: 23, direction: 'right', state: 'run0' },
		{ rockX: 25, direction: 'right', state: 'run1' },
		{ rockX: 26, direction: 'right', state: 'run1' },
		{ rockX: 28, direction: 'right', state: 'run1' },
		{ rockX: 29, direction: 'right', state: 'run1' },
		{ rockX: 31, direction: 'right', state: 'run1' },
		{ rockX: 32, direction: 'right', state: 'run1' },
		{ rockX: 34, direction: 'right', state: 'run1' },
		{ rockX: 35, direction: 'right', state: 'run2' },
		{ rockX: 37, direction: 'right', state: 'run2' },
		{ rockX: 38, direction: 'right', state: 'run2' },
		{ rockX: 40, direction: 'right', state: 'run2' },
		{ rockX: 41, direction: 'right', state: 'run2' },
		{ rockX: 43, direction: 'right', state: 'run2' },
		{ rockX: 44, direction: 'right', state: 'run2' },
		{ rockX: 46, direction: 'right', state: 'run1' },
		{ rockX: 47, direction: 'right', state: 'run1' },
		{ rockX: 49, direction: 'right', state: 'run1' },
		{ rockX: 50, direction: 'right', state: 'run1' },
		{ rockX: 52, direction: 'right', state: 'run1' },
		{ rockX: 53, direction: 'right', state: 'run1' },
		{ rockX: 55, direction: 'right', state: 'run1' },
		{ rockX: 56, direction: 'right', state: 'run0' },
		{ rockX: 58, direction: 'right', state: 'run0' },
		{ rockX: 59, direction: 'right', state: 'run0' },
		{ rockX: 61, direction: 'right', state: 'run0' },
		{ rockX: 62, direction: 'right', state: 'run0' },
		{ rockX: 64, direction: 'right', state: 'run0' },
		{ rockX: 65, direction: 'right', state: 'run0' },
		{ rockX: 67, direction: 'right', state: 'run1' },
		{ rockX: 68, direction: 'right', state: 'run1' },
		{ rockX: 70, direction: 'right', state: 'run1' },
		{ rockX: 71, direction: 'right', state: 'run1' },
		{ rockX: 73, direction: 'right', state: 'run1' },
		{ rockX: 74, direction: 'right', state: 'run1' },
		{ rockX: 76, direction: 'right', state: 'run1' },
		{ rockX: 77, direction: 'right', state: 'run2' },
		{ rockX: 79, direction: 'right', state: 'run2' },
		{ rockX: 80, direction: 'right', state: 'run2' },
		{ rockX: 82, direction: 'right', state: 'run2' },
		{ rockX: 83, direction: 'right', state: 'run2' },
		{ rockX: 85, direction: 'right', state: 'run2' },
		{ rockX: 86, direction: 'right', state: 'run2' },
		{ rockX: 88, direction: 'right', state: 'run1' },
		{ rockX: 89, direction: 'right', state: 'run1' },
		{ rockX: 91, direction: 'right', state: 'run1' },
		{ rockX: 92, direction: 'right', state: 'run1' },
		{ rockX: 94, direction: 'right', state: 'run1' },
		{ rockX: 95, direction: 'right', state: 'run1' },
		{ rockX: 97, direction: 'right', state: 'run1' },
		{ rockX: 98, direction: 'right', state: 'run0' },
		{ rockX: 100, direction: 'right', state: 'run0' },
		{ rockX: 101, direction: 'right', state: 'run0' },
		{ rockX: 103, direction: 'right', state: 'run0' },
		{ rockX: 104, direction: 'right', state: 'run0' },
		{ rockX: 106, direction: 'right', state: 'run0' },
		{ rockX: 107, direction: 'right', state: 'run0' },
		{ rockX: 109, direction: 'right', state: 'run1' },
		{ rockX: 110, direction: 'right', state: 'run1' },
		{ rockX: 112, direction: 'right', state: 'run1' },
		{ rockX: 113, direction: 'right', state: 'run1' },
		{ rockX: 115, direction: 'right', state: 'run1' },
		{ rockX: 116, direction: 'right', state: 'run1' },
		{ rockX: 118, direction: 'right', state: 'run1' },
		{ rockX: 119, direction: 'right', state: 'run2' },
		{ rockX: 121, direction: 'right', state: 'run2' },
		{ rockX: 122, direction: 'right', state: 'run2' },
		{ rockX: 122, direction: 'right', state: 'run2' },
		{ rockX: 123, direction: 'right', state: 'run2' },
		{ rockX: 123, direction: 'right', state: 'run2' },
		{ rockX: 124, direction: 'right', state: 'run2' },
		{ rockX: 124, direction: 'right', state: 'run2' },
		{ rockX: 125, direction: 'right', state: 'run2' },
		{ rockX: 125, direction: 'right', state: 'pull' },
		{ rockX: 126, direction: 'right', state: 'pull' },
		{ rockX: 126, direction: 'right', state: 'pull' },
		{ rockX: 127, direction: 'right', state: 'pull' },
		{ rockX: 127, direction: 'right', state: 'pull' },
		{ rockX: 128, direction: 'right', state: 'pull' },
		{ rockX: 128, direction: 'right', state: 'normal' },
		{ rockX: 128, direction: 'right', state: 'normal' },
		{ rockX: 128, direction: 'right', state: 'normal' },
		{ rockX: 128, direction: 'left', state: 'normal' },
	],
	RIGHT_TO_LEFT_FRAMES: [
		{ rockX: 128, direction: 'left', state: 'normal' },
		{ rockX: 128, direction: 'left', state: 'normal' },
		{ rockX: 128, direction: 'left', state: 'normal' },
		{ rockX: 128, direction: 'left', state: 'normal' },
		{ rockX: 128, direction: 'left', state: 'normal' },
		{ rockX: 128, direction: 'left', state: 'pull' },
		{ rockX: 128, direction: 'left', state: 'pull' },
		{ rockX: 128, direction: 'left', state: 'pull' },
		{ rockX: 128, direction: 'left', state: 'pull' },
		{ rockX: 128, direction: 'left', state: 'pull' },
		{ rockX: 127, direction: 'left', state: 'run0' },
		{ rockX: 125, direction: 'left', state: 'run0' },
		{ rockX: 124, direction: 'left', state: 'run0' },
		{ rockX: 122, direction: 'left', state: 'run0' },
		{ rockX: 121, direction: 'left', state: 'run0' },
		{ rockX: 119, direction: 'left', state: 'run0' },
		{ rockX: 118, direction: 'left', state: 'run0' },
		{ rockX: 116, direction: 'left', state: 'run1' },
		{ rockX: 115, direction: 'left', state: 'run1' },
		{ rockX: 113, direction: 'left', state: 'run1' },
		{ rockX: 112, direction: 'left', state: 'run1' },
		{ rockX: 112, direction: 'left', state: 'run1' },
		{ rockX: 111, direction: 'left', state: 'run1' },
		{ rockX: 111, direction: 'left', state: 'run1' },
		{ rockX: 110, direction: 'left', state: 'run1' },
		{ rockX: 110, direction: 'left', state: 'run1' },
		{ rockX: 109, direction: 'left', state: 'run1' },
		{ rockX: 109, direction: 'left', state: 'pull' },
		{ rockX: 108, direction: 'left', state: 'pull' },
		{ rockX: 108, direction: 'left', state: 'pull' },
		{ rockX: 107, direction: 'left', state: 'pull' },
		{ rockX: 107, direction: 'left', state: 'pull' },
		{ rockX: 106, direction: 'left', state: 'pull' },
		{ rockX: 106, direction: 'left', state: 'normal' },
		{ rockX: 106, direction: 'left', state: 'normal' },
		{ rockX: 106, direction: 'left', state: 'normal' },
		{ rockX: 106, direction: 'right', state: 'normal' },
	],
	LEFT_TO_RIGHT_FRAMES: [
		{ rockX: 106, direction: 'right', state: 'normal' },
		{ rockX: 106, direction: 'right', state: 'normal' },
		{ rockX: 106, direction: 'right', state: 'normal' },
		{ rockX: 106, direction: 'right', state: 'normal' },
		{ rockX: 106, direction: 'right', state: 'normal' },
		{ rockX: 106, direction: 'right', state: 'pull' },
		{ rockX: 106, direction: 'right', state: 'pull' },
		{ rockX: 106, direction: 'right', state: 'pull' },
		{ rockX: 106, direction: 'right', state: 'pull' },
		{ rockX: 106, direction: 'right', state: 'pull' },
		{ rockX: 107, direction: 'right', state: 'run0' },
		{ rockX: 109, direction: 'right', state: 'run0' },
		{ rockX: 110, direction: 'right', state: 'run0' },
		{ rockX: 112, direction: 'right', state: 'run0' },
		{ rockX: 113, direction: 'right', state: 'run0' },
		{ rockX: 115, direction: 'right', state: 'run0' },
		{ rockX: 116, direction: 'right', state: 'run0' },
		{ rockX: 118, direction: 'right', state: 'run1' },
		{ rockX: 119, direction: 'right', state: 'run1' },
		{ rockX: 121, direction: 'right', state: 'run1' },
		{ rockX: 122, direction: 'right', state: 'run1' },
		{ rockX: 122, direction: 'right', state: 'run1' },
		{ rockX: 123, direction: 'right', state: 'run1' },
		{ rockX: 123, direction: 'right', state: 'run1' },
		{ rockX: 124, direction: 'right', state: 'run1' },
		{ rockX: 124, direction: 'right', state: 'run1' },
		{ rockX: 125, direction: 'right', state: 'run1' },
		{ rockX: 125, direction: 'right', state: 'pull' },
		{ rockX: 126, direction: 'right', state: 'pull' },
		{ rockX: 126, direction: 'right', state: 'pull' },
		{ rockX: 127, direction: 'right', state: 'pull' },
		{ rockX: 127, direction: 'right', state: 'pull' },
		{ rockX: 128, direction: 'right', state: 'pull' },
		{ rockX: 128, direction: 'right', state: 'normal' },
		{ rockX: 128, direction: 'right', state: 'normal' },
		{ rockX: 128, direction: 'right', state: 'normal' },
		{ rockX: 128, direction: 'left', state: 'normal' },
	],
	JUMP_3FRAMES: [
		//{ rockY: 137, state: 'jump' },
		{ rockY: 132, state: 'jump' },
		{ rockY: 128, state: 'jump' },
		{ rockY: 127, state: 'jump' },
		{ rockY: 126, state: 'jump' },
		{ rockY: 125, state: 'jump' },
		{ rockY: 125, state: 'jump' },
		{ rockY: 125, state: 'jump' },
		{ rockY: 125, state: 'jump' },
		{ rockY: 126, state: 'jump' },
		{ rockY: 127, state: 'jump' },
		{ rockY: 128, state: 'jump' },
		{ rockY: 129, state: 'jump' },
		{ rockY: 130, state: 'jump' },
		{ rockY: 132, state: 'jump' },
		{ rockY: 134, state: 'jump' },
		{ rockY: 136, state: 'jump' },
		{ rockY: 139, state: 'jump' },
		{ rockY: 137, state: 'run2' },
		{ rockY: 137, state: 'run0' },
		{ rockY: 137, state: 'run0' },
		{ rockY: 137, state: 'normal' },
	],
	JUMP_4FRAMES: [
		//{ rockY: 137, state: 'jump' },
		{ rockY: 132, state: 'jump' },
		{ rockY: 128, state: 'jump' },
		{ rockY: 124, state: 'jump' },
		{ rockY: 123, state: 'jump' },
		{ rockY: 122, state: 'jump' },
		{ rockY: 121, state: 'jump' },
		{ rockY: 121, state: 'jump' },
		{ rockY: 121, state: 'jump' },
		{ rockY: 121, state: 'jump' },
		{ rockY: 122, state: 'jump' },
		{ rockY: 123, state: 'jump' },
		{ rockY: 124, state: 'jump' },
		{ rockY: 125, state: 'jump' },
		{ rockY: 126, state: 'jump' },
		{ rockY: 128, state: 'jump' },
		{ rockY: 130, state: 'jump' },
		{ rockY: 132, state: 'jump' },
		{ rockY: 135, state: 'jump' },
		{ rockY: 138, state: 'jump' },
		{ rockY: 141, state: 'jump' },
		{ rockY: 137, state: 'run2' },
		{ rockY: 137, state: 'run0' },
		{ rockY: 137, state: 'run0' },
		{ rockY: 137, state: 'normal' },
	],
	JUMP_5FRAMES: [
		//{ rockY: 137, state: 'jump' },
		{ rockY: 132, state: 'jump' },
		{ rockY: 128, state: 'jump' },
		{ rockY: 124, state: 'jump' },
		{ rockY: 120, state: 'jump' },
		{ rockY: 119, state: 'jump' },
		{ rockY: 118, state: 'jump' },
		{ rockY: 117, state: 'jump' },
		{ rockY: 117, state: 'jump' },
		{ rockY: 117, state: 'jump' },
		{ rockY: 117, state: 'jump' },
		{ rockY: 118, state: 'jump' },
		{ rockY: 119, state: 'jump' },
		{ rockY: 120, state: 'jump' },
		{ rockY: 121, state: 'jump' },
		{ rockY: 122, state: 'jump' },
		{ rockY: 124, state: 'jump' },
		{ rockY: 126, state: 'jump' },
		{ rockY: 128, state: 'jump' },
		{ rockY: 131, state: 'jump' },
		{ rockY: 134, state: 'jump' },
		{ rockY: 137, state: 'jump' },
		{ rockY: 140, state: 'jump' },
		{ rockY: 137, state: 'run2' },
		{ rockY: 137, state: 'run0' },
		{ rockY: 137, state: 'run0' },
		{ rockY: 137, state: 'normal' },
	],
	JUMP_6FRAMES: [
		//{ rockY: 137, state: 'jump' },
		{ rockY: 132, state: 'jump' },
		{ rockY: 128, state: 'jump' },
		{ rockY: 124, state: 'jump' },
		{ rockY: 120, state: 'jump' },
		{ rockY: 116, state: 'jump' },
		{ rockY: 115, state: 'jump' },
		{ rockY: 114, state: 'jump' },
		{ rockY: 114, state: 'jump' },
		{ rockY: 114, state: 'jump' },
		{ rockY: 114, state: 'jump' },
		{ rockY: 114, state: 'jump' },
		{ rockY: 114, state: 'jump' },
		{ rockY: 115, state: 'jump' },
		{ rockY: 116, state: 'jump' },
		{ rockY: 117, state: 'jump' },
		{ rockY: 119, state: 'jump' },
		{ rockY: 121, state: 'jump' },
		{ rockY: 123, state: 'jump' },
		{ rockY: 125, state: 'jump' },
		{ rockY: 127, state: 'jump' },
		{ rockY: 130, state: 'jump' },
		{ rockY: 133, state: 'jump' },
		{ rockY: 136, state: 'jump' },
		{ rockY: 140, state: 'jump' },
		{ rockY: 137, state: 'run2' },
		{ rockY: 137, state: 'run0' },
		{ rockY: 137, state: 'run0' },
		{ rockY: 137, state: 'normal' },
	],
	JUMP_7FRAMES: [
		//{ rockY: 137, state: 'jump' },
		{ rockY: 132, state: 'jump' },
		{ rockY: 128, state: 'jump' },
		{ rockY: 124, state: 'jump' },
		{ rockY: 120, state: 'jump' },
		{ rockY: 116, state: 'jump' },
		{ rockY: 113, state: 'jump' },
		{ rockY: 112, state: 'jump' },
		{ rockY: 111, state: 'jump' },
		{ rockY: 110, state: 'jump' },
		{ rockY: 110, state: 'jump' },
		{ rockY: 110, state: 'jump' },
		{ rockY: 110, state: 'jump' },
		{ rockY: 111, state: 'jump' },
		{ rockY: 112, state: 'jump' },
		{ rockY: 113, state: 'jump' },
		{ rockY: 114, state: 'jump' },
		{ rockY: 115, state: 'jump' },
		{ rockY: 117, state: 'jump' },
		{ rockY: 119, state: 'jump' },
		{ rockY: 121, state: 'jump' },
		{ rockY: 124, state: 'jump' },
		{ rockY: 127, state: 'jump' },
		{ rockY: 130, state: 'jump' },
		{ rockY: 133, state: 'jump' },
		{ rockY: 136, state: 'jump' },
		{ rockY: 140, state: 'jump' },
		{ rockY: 137, state: 'run2' },
		{ rockY: 137, state: 'run0' },
		{ rockY: 137, state: 'run0' },
		{ rockY: 137, state: 'normal' },
	],
	JUMP_8FRAMES:[
		//{ rockY: 137, state: 'jump' },
		{ rockY: 132, state: 'jump' },
		{ rockY: 128, state: 'jump' },
		{ rockY: 124, state: 'jump' },
		{ rockY: 120, state: 'jump' },
		{ rockY: 116, state: 'jump' },
		{ rockY: 113, state: 'jump' },
		{ rockY: 110, state: 'jump' },
		{ rockY: 109, state: 'jump' },
		{ rockY: 108, state: 'jump' },
		{ rockY: 107, state: 'jump' },
		{ rockY: 107, state: 'jump' },
		{ rockY: 107, state: 'jump' },
		{ rockY: 107, state: 'jump' },
		{ rockY: 108, state: 'jump' },
		{ rockY: 109, state: 'jump' },
		{ rockY: 110, state: 'jump' },
		{ rockY: 111, state: 'jump' },
		{ rockY: 112, state: 'jump' },
		{ rockY: 114, state: 'jump' },
		{ rockY: 116, state: 'jump' },
		{ rockY: 118, state: 'jump' },
		{ rockY: 121, state: 'jump' },
		{ rockY: 124, state: 'jump' },
		{ rockY: 127, state: 'jump' },
		{ rockY: 130, state: 'jump' },
		{ rockY: 133, state: 'jump' },
		{ rockY: 137, state: 'jump' },
		{ rockY: 141, state: 'jump' },
		{ rockY: 137, state: 'run2' },
		{ rockY: 137, state: 'run0' },
		{ rockY: 137, state: 'run0' },
		{ rockY: 137, state: 'normal' },
	],
	JUMP_9FRAMES: [
		//{ rockY: 137, state: 'jump' },
		{ rockY: 132, state: 'jump' },
		{ rockY: 128, state: 'jump' },
		{ rockY: 124, state: 'jump' },
		{ rockY: 120, state: 'jump' },
		{ rockY: 116, state: 'jump' },
		{ rockY: 113, state: 'jump' },
		{ rockY: 110, state: 'jump' },
		{ rockY: 107, state: 'jump' },
		{ rockY: 106, state: 'jump' },
		{ rockY: 105, state: 'jump' },
		{ rockY: 104, state: 'jump' },
		{ rockY: 104, state: 'jump' },
		{ rockY: 104, state: 'jump' },
		{ rockY: 104, state: 'jump' },
		{ rockY: 105, state: 'jump' },
		{ rockY: 106, state: 'jump' },
		{ rockY: 107, state: 'jump' },
		{ rockY: 108, state: 'jump' },
		{ rockY: 109, state: 'jump' },
		{ rockY: 111, state: 'jump' },
		{ rockY: 113, state: 'jump' },
		{ rockY: 115, state: 'jump' },
		{ rockY: 118, state: 'jump' },
		{ rockY: 121, state: 'jump' },
		{ rockY: 124, state: 'jump' },
		{ rockY: 127, state: 'jump' },
		{ rockY: 130, state: 'jump' },
		{ rockY: 134, state: 'jump' },
		{ rockY: 138, state: 'jump' },
		{ rockY: 137, state: 'run2' },
		{ rockY: 137, state: 'run0' },
		{ rockY: 137, state: 'run0' },
		{ rockY: 137, state: 'normal' },
	],

	JUMP_10FRAMES: [
		//{ rockY: 137, state: 'jump' },
		{ rockY: 132, state: 'jump' },
		{ rockY: 128, state: 'jump' },
		{ rockY: 124, state: 'jump' },
		{ rockY: 120, state: 'jump' },
		{ rockY: 116, state: 'jump' },
		{ rockY: 113, state: 'jump' },
		{ rockY: 110, state: 'jump' },
		{ rockY: 107, state: 'jump' },
		{ rockY: 104, state: 'jump' },
		{ rockY: 103, state: 'jump' },
		{ rockY: 102, state: 'jump' },
		{ rockY: 102, state: 'jump' },
		{ rockY: 102, state: 'jump' },
		{ rockY: 102, state: 'jump' },
		{ rockY: 102, state: 'jump' },
		{ rockY: 102, state: 'jump' },
		{ rockY: 103, state: 'jump' },
		{ rockY: 104, state: 'jump' },
		{ rockY: 105, state: 'jump' },
		{ rockY: 107, state: 'jump' },
		{ rockY: 109, state: 'jump' },
		{ rockY: 111, state: 'jump' },
		{ rockY: 113, state: 'jump' },
		{ rockY: 115, state: 'jump' },
		{ rockY: 118, state: 'jump' },
		{ rockY: 121, state: 'jump' },
		{ rockY: 124, state: 'jump' },
		{ rockY: 128, state: 'jump' },
		{ rockY: 132, state: 'jump' },
		{ rockY: 136, state: 'jump' },
		{ rockY: 140, state: 'jump' },
		{ rockY: 137, state: 'run2' },
		{ rockY: 137, state: 'run0' },
		{ rockY: 137, state: 'run0' },
		{ rockY: 137, state: 'normal' },
	],
	JUMP_11FRAMES:[
		//{ rockY: 137, state: 'jump' },
		{ rockY: 132, state: 'jump' },
		{ rockY: 128, state: 'jump' },
		{ rockY: 124, state: 'jump' },
		{ rockY: 120, state: 'jump' },
		{ rockY: 116, state: 'jump' },
		{ rockY: 113, state: 'jump' },
		{ rockY: 110, state: 'jump' },
		{ rockY: 107, state: 'jump' },
		{ rockY: 104, state: 'jump' },
		{ rockY: 102, state: 'jump' },
		{ rockY: 101, state: 'jump' },
		{ rockY: 100, state: 'jump' },
		{ rockY: 99, state: 'jump' },
		{ rockY: 99, state: 'jump' },
		{ rockY: 99, state: 'jump' },
		{ rockY: 99, state: 'jump' },
		{ rockY: 100, state: 'jump' },
		{ rockY: 101, state: 'jump' },
		{ rockY: 102, state: 'jump' },
		{ rockY: 103, state: 'jump' },
		{ rockY: 104, state: 'jump' },
		{ rockY: 106, state: 'jump' },
		{ rockY: 108, state: 'jump' },
		{ rockY: 110, state: 'jump' },
		{ rockY: 113, state: 'jump' },
		{ rockY: 116, state: 'jump' },
		{ rockY: 119, state: 'jump' },
		{ rockY: 122, state: 'jump' },
		{ rockY: 125, state: 'jump' },
		{ rockY: 129, state: 'jump' },
		{ rockY: 133, state: 'jump' },
		{ rockY: 137, state: 'jump' },
		{ rockY: 137, state: 'run2' },
		{ rockY: 137, state: 'run0' },
		{ rockY: 137, state: 'run0' },
		{ rockY: 137, state: 'normal' },
	],
	JUMP_12FRAMES: [
		//{ rockY: 137, state: 'jump' },
		{ rockY: 132, state: 'jump' },
		{ rockY: 128, state: 'jump' },
		{ rockY: 124, state: 'jump' },
		{ rockY: 120, state: 'jump' },
		{ rockY: 116, state: 'jump' },
		{ rockY: 113, state: 'jump' },
		{ rockY: 110, state: 'jump' },
		{ rockY: 107, state: 'jump' },
		{ rockY: 104, state: 'jump' },
		{ rockY: 102, state: 'jump' },
		{ rockY: 100, state: 'jump' },
		{ rockY: 98, state: 'jump' },
		{ rockY: 96, state: 'jump' },
		{ rockY: 95, state: 'jump' },
		{ rockY: 94, state: 'jump' },
		{ rockY: 93, state: 'jump' },
		{ rockY: 92, state: 'jump' },
		{ rockY: 92, state: 'jump' },
		{ rockY: 92, state: 'jump' },
		{ rockY: 92, state: 'jump' },
		{ rockY: 92, state: 'jump' },
		{ rockY: 93, state: 'jump' },
		{ rockY: 94, state: 'jump' },
		{ rockY: 95, state: 'jump' },
		{ rockY: 96, state: 'jump' },
		{ rockY: 98, state: 'jump' },
		{ rockY: 100, state: 'jump' },
		{ rockY: 102, state: 'jump' },
		{ rockY: 104, state: 'jump' },
		{ rockY: 107, state: 'jump' },
		{ rockY: 110, state: 'jump' },
		{ rockY: 113, state: 'jump' },
		{ rockY: 116, state: 'jump' },
		{ rockY: 120, state: 'jump' },
		{ rockY: 124, state: 'jump' },
		{ rockY: 128, state: 'jump' },
		{ rockY: 132, state: 'jump' },
		{ rockY: 137, state: 'jump' },
		{ rockY: 137, state: 'run2' },
		{ rockY: 137, state: 'run0' },
		{ rockY: 137, state: 'run0' },
		{ rockY: 137, state: 'normal' },
	],
	IDLE_FRAMES: [
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'normal' },
		{ state: 'blink' },
		{ state: 'blink' },
		{ state: 'blink' },
		{ state: 'blink' },
		{ state: 'blink' },
		{ state: 'blink' },
		{ state: 'blink' },
		{ state: 'blink' },
		{ state: 'blink' },
	],
	// ショットは15F
	JUMP_SHOT_8FRAMES:[
		//{ rockY: 137, state: 'jump' },
		{ rockY: 132, state: 'jump' },
		{ rockY: 128, state: 'jump' },
		{ rockY: 124, state: 'jump' },
		{ rockY: 120, state: 'jump' },
		{ rockY: 116, state: 'jump' },
		{ rockY: 113, state: 'jumpshot' },
		{ rockY: 110, state: 'jumpshot' },
		{ rockY: 109, state: 'jumpshot' },
		{ rockY: 108, state: 'jumpshot' },
		{ rockY: 107, state: 'jumpshot' },
		{ rockY: 107, state: 'jumpshot' },
		{ rockY: 107, state: 'jumpshot' },
		{ rockY: 107, state: 'jumpshot' },
		{ rockY: 108, state: 'jumpshot' },
		{ rockY: 109, state: 'jumpshot' },
		{ rockY: 110, state: 'jumpshot' },
		{ rockY: 111, state: 'jumpshot' },
		{ rockY: 112, state: 'jumpshot' },
		{ rockY: 114, state: 'jumpshot' },
		{ rockY: 116, state: 'jumpshot' },
		{ rockY: 118, state: 'jump' },
		{ rockY: 121, state: 'jump' },
		{ rockY: 124, state: 'jump' },
		{ rockY: 127, state: 'jump' },
		{ rockY: 130, state: 'jump' },
		{ rockY: 133, state: 'jump' },
		{ rockY: 137, state: 'jump' },
		{ rockY: 141, state: 'jump' },
		{ rockY: 137, state: 'run2' },
		{ rockY: 137, state: 'run0' },
		{ rockY: 137, state: 'run0' },
		{ rockY: 137, state: 'normal' },
	],

	JUMP_SHOT_12FRAMES: [
		//{ rockY: 137, state: 'jump' },
		{ rockY: 132, state: 'jump' },
		{ rockY: 128, state: 'jump' },
		{ rockY: 124, state: 'jump' },
		{ rockY: 120, state: 'jump' },
		{ rockY: 116, state: 'jump' },
		{ rockY: 113, state: 'jump' },
		{ rockY: 110, state: 'jump' },
		{ rockY: 107, state: 'jump' },
		{ rockY: 104, state: 'jump' },
		{ rockY: 102, state: 'jump' },
		{ rockY: 100, state: 'jump' },
		{ rockY: 98, state: 'jump' },// ここで打つ
		{ rockY: 96, state: 'jumpshot' },
		{ rockY: 95, state: 'jumpshot' },
		{ rockY: 94, state: 'jumpshot' },
		{ rockY: 93, state: 'jumpshot' },
		{ rockY: 92, state: 'jumpshot' },
		{ rockY: 92, state: 'jumpshot' },
		{ rockY: 92, state: 'jumpshot' },
		{ rockY: 92, state: 'jumpshot' },
		{ rockY: 92, state: 'jumpshot' },
		{ rockY: 93, state: 'jumpshot' },
		{ rockY: 94, state: 'jumpshot' },
		{ rockY: 95, state: 'jumpshot' },
		{ rockY: 96, state: 'jumpshot' },
		{ rockY: 98, state: 'jumpshot' },
		{ rockY: 100, state: 'jumpshot' },
		{ rockY: 102, state: 'jump' },
		{ rockY: 104, state: 'jump' },
		{ rockY: 107, state: 'jump' },
		{ rockY: 110, state: 'jump' },
		{ rockY: 113, state: 'jump' },
		{ rockY: 116, state: 'jump' },
		{ rockY: 120, state: 'jump' },
		{ rockY: 124, state: 'jump' },
		{ rockY: 128, state: 'jump' },
		{ rockY: 132, state: 'jump' },
		{ rockY: 137, state: 'jump' },
		{ rockY: 137, state: 'run2' },
		{ rockY: 137, state: 'run0' },
		{ rockY: 137, state: 'run0' },
		{ rockY: 137, state: 'normal' },
	],
};